### PR TITLE
ensure that section has a path attribute

### PR DESCRIPTION
**Pull request by wbowling**
## Fix error when using telescope##
Occasionall would get the following:
`[!] Command 'dereference' failed to execute properly, reason: 'NoneType' object has no attribute 'path'`

### Description/Motivation/Screenshots ###
Was broken in https://github.com/hugsy/gef/commit/edbadbef7813fb96827572fcac3db35c9550beaa

### Checklist ###
- [x] My code follows the code style of this project.
- [x] My change includes a change to the documentation, if required.
- [x] I have read and agree to the **CONTRIBUTING** document.

---
This change is [Reviewable](https://reviewable.io/reviews/hugsy/gef/287)

### CODE REVIEW

**Comment by Grazfather** [comment]
Thanks man
