### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'major'

### ISSUE THREAD

**Issue by crackeer** [hugsy/gef#42]
Traceback (most recent call last):
  File "/root/.gdbinit-gef.py", line 61, in <module>
    if sys.version_info.major == 2:
AttributeError: 'tuple' object has no attribute 'major'

**Comment by hugsy** [comment]
What is your version of Python compiled with gdb ?

**Comment by crackeer** [comment]
gdb version 7.2
python version 2.7.12

**Comment by hugsy** [comment]
That sounds weird. Did you compile it yourself ? I am talking of the Python version compiled with your gdb, not your standalone Python.

**Comment by xarkes** [comment]
It should be working with python >= 2.7 however you can fix this using ```if sys.version_info[0] == 2:``` instead of ```if sys.version_info.major == 2:```
