### ISSUE TITLE
Problem to run heap command

### ISSUE THREAD

**Issue by ghbpeter** [hugsy/gef#568]
Your issue will be closed unless you confirm the following (insert `x` in the brackets if done/agreed):
  * [x ] Did you use the latest version of GEF from `master` branch?
  * [ x] Did you read the [documentation](https://gef.readthedocs.org/en/latest/) first?
  * [x ] Did you check [issues](https://github.com/hugsy/gef/issues) (including the closed ones) - and the [PR](https://github.com/hugsy/gef/pulls)?

### Step 1: Describe your environment

  * Operating System / Distribution: Ubuntu 18.04 
  * Architecture: amd64
  * GDB version (including the Python library version) copy the output of `$ gdb -ex "pi import sys;print(gdb.VERSION);print(sys.version)"`: 

8.1.0.20180409-git
3.6.9 (default, Jul 17 2020, 12:50:27) 

### Step 2: Describe your problem
After starting gdb with "gdb attach PID" exception appears, and not possible tu run heap command:
Attaching to process 8140
[New LWP 8141]
Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'all_registers': 
[New LWP 8142]
Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'all_registers': 
[New LWP 8143]
Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'all_registers': 
...
gef➤  heap arenas
[!] Command 'heap arenas' failed to execute properly, reason: There is no member named last_remainder.

#### Steps to reproduce
1. Installed both python 2.7 and python3
2. Installed by documentation
3. gdb attached to process 
4. Trying to run heap command

**Comment by Grazfather** [comment]
This isn't an with the heap command, you get the error sooner.

You aren't attaching correctly. Please read the docs before filing issues. https://gef.readthedocs.io/en/master/commands/gef-remote/

**Comment by ghbpeter** [comment]
It is not remote debugging. Even when I don't use attaching and I start debugging with gdb /path_to_debug_binary I receive "Command 'heap arenas' failed to execute properly, reason: There is no member named last_remainder." Debug symbols are right, I can normally step through C sources.
I am new in python. Maybe it has something with python version ? I have installed both python 2.7.17 and python 3.6.9 and by default is used python 3.6.9.
I found that last_remainder is property of class class MallocStateStruct(object) but no idea why command heap outputs above error.

**Comment by Grazfather** [comment]
Sorry, I was tired and misread.

This is likely to do with a version of libc being used. 

`'NoneType' object has no attribute 'all_registers':` suggests that the `current_arch` is not being selected properly. You can try manually setting the architecture.

I suggest you try running gef in docker.

You can use this docker file: https://github.com/Grazfather/mypwndock, which installs gef.

Try to get it working with a normal binary first, such as `/bin/cat`. It's very strange for it to not work on 18.04

**Comment by ghbpeter** [comment]
I removed all python 2.7 packages and now exception above is not present.
But with my application "heap arenas" still I have output: "Command 'heap arenas' failed to execute properly, reason: There is no member named last_remainder.".

I tried this:
I printed architecture and it is: "i386:x86-64", OK.
I tried different application and "heap arenas" output was OK, heap area is functional with it !

So I am trying to find what is different with my application and another application which is understood by GEF.
My application uses memory hugepages by default. I rebuilt it to not use hugetlb. Still no success.

Have you please some idea what to check ?

**Comment by hugsy** [comment]
`heap` commands in GEF work with glibc only, and require to have the symbol of at least the `main_arena` exported by it; and work only for the default `ptmalloc2` allocator.

Try the command:
```
gef ➤  display main_arena
2: main_arena = {
  mutex = 0x0,
  flags = 0x0,
  have_fastchunks = 0x0,
  fastbinsY = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
  top = 0x555555579900,
  last_remainder = 0x0,
[...]
```

Other libcs (musl, uclibc, dietlibc, etc.) are not supported and are not planned to be.

**Comment by theguy147** [comment]
@ghbpeter i know this issue was opened a long time ago, but do you still have this issue on the latest `dev` branch?  Or can it be closed?

**Comment by itsallmathematics** [comment]
FYI to others:

I actually got this `'NoneType' object has no attribute 'all_registers'` error when I had (essentially) typos in my `~/.gef.rc` file. So if you get this error, make sure your `~/.gef.rc` is configured properly too.
